sparse_matrix: src/sparse/matrix_gtest.cpp File Reference
matrix_gtest.cpp File Reference
#include <gtest/gtest.h>
#include <sstream>
#include <algorithm>
#include "matrix.hpp"
Functions
TEST (sparse_matrix, create_empty)
TEST (sparse_matrix, check_default_value)
TEST (sparse_matrix, assign)
TEST (sparse_matrix, default_value_assignmen)
TEST (sparse_matrix, iteration1)
TEST (sparse_matrix, iteration2)
TEST (sparse_matrix, reassignment)
TEST (sparse_matrix, dim1)
TEST (sparse_matrix, dim3)
Function Documentation
TEST() [1/9]
TEST (sparse_matrix , assign)
Definition at line 23 of file matrix_gtest.cpp.
{
  sparse::Matrix<int> m;
  m[100][100] = 314;
  ASSERT_EQ(m[100][100], 314);
  ASSERT_EQ(m.size(), 1);
}
References sparse::Matrix< T, N_DIMS >::size().
TEST() [2/9]
TEST (sparse_matrix , check_default_value)
Definition at line 15 of file matrix_gtest.cpp.
{
  constexpr int default_value = -1;
  sparse::Matrix<int> matrix(default_value);
  ASSERT_EQ(matrix[0][0], default_value);
  ASSERT_EQ(matrix[1000][20000], default_value);
  ASSERT_EQ(matrix.size(), 0);
}
References sparse::Matrix< T, N_DIMS >::size().
TEST() [3/9]
TEST (sparse_matrix , create_empty)
Definition at line 10 of file matrix_gtest.cpp.
{
  sparse::Matrix<int> matrix;
  ASSERT_EQ(matrix.size(), 0);
}
References sparse::Matrix< T, N_DIMS >::size().
TEST() [4/9]
TEST (sparse_matrix , default_value_assignmen)
Definition at line 30 of file matrix_gtest.cpp.
{
  constexpr int default_value = -1;
  sparse::Matrix<int> matrix(default_value);
  ASSERT_EQ(matrix.size(), 0);
  matrix[100][100] = 314;
  ASSERT_EQ(matrix.size(), 1);
  matrix[100][100] = default_value;
  ASSERT_EQ(matrix.size(), 0);
}
References sparse::Matrix< T, N_DIMS >::size().
TEST() [5/9]
TEST (sparse_matrix , dim1)
Definition at line 75 of file matrix_gtest.cpp.
{
  constexpr int default_value = -1;
  sparse::Matrix<int, 1> matrix(default_value);
  ASSERT_EQ(matrix[1000], default_value);
  ASSERT_EQ(matrix.size(), 0);
  matrix[100] = 314;
  ASSERT_EQ(matrix[100], 314);
  ASSERT_EQ(matrix[1000], default_value);
  ASSERT_EQ(matrix.size(), 1);
  matrix[100] = default_value;
  ASSERT_EQ(matrix[100], default_value);
  ASSERT_EQ(matrix.size(), 0);
}
References sparse::Matrix< T, N_DIMS >::size().
TEST() [6/9]
TEST (sparse_matrix , dim3)
Definition at line 89 of file matrix_gtest.cpp.
{
  constexpr int default_value = -1;
  sparse::Matrix<int, 3> matrix(default_value);
  ASSERT_EQ(matrix[1000][2000][3000], default_value);
  ASSERT_EQ(matrix.size(), 0);
  matrix[1000][2000][3000] = 314;
  ASSERT_EQ(matrix[1000][2000][3000], 314);
  ASSERT_EQ(matrix[1000][2000][30000], default_value);
  ASSERT_EQ(matrix.size(), 1);
  matrix[1000][2000][3000] = default_value;
  ASSERT_EQ(matrix[1000][2000][3000], default_value);
  ASSERT_EQ(matrix.size(), 0);
}
References sparse::Matrix< T, N_DIMS >::size().
TEST() [7/9]
TEST (sparse_matrix , iteration1)
Definition at line 40 of file matrix_gtest.cpp.
{
  sparse::Matrix<int> matrix;
  matrix[100][200] = 314;
  std::stringstream ss;
  for(auto const& cell: matrix)
  {
    auto const& [idx, v] = cell;
    auto const& [x, y] = idx;
    ss << x << ":" << y << "=" << v;
  }
  ASSERT_EQ(ss.str(), "100:200=314");
}
TEST() [8/9]
TEST (sparse_matrix , iteration2)
Definition at line 53 of file matrix_gtest.cpp.
{
  sparse::Matrix<int> matrix;
  matrix[10][100] = 11;
  matrix[20][200] = 22;
  matrix[30][300] = 33;
  std::stringstream ss;
  // for (auto const& e: matrix) {
  //   auto const& [x, y, v] = e;
  //   ss << x << y << v << "\n";
  // }
  // ASSERT_EQ(ss.str(), "1010011\n2020022\n3030033\n");
  ss << matrix;
  ASSERT_EQ(ss.str(), "[10,100]=11\n[20,200]=22\n[30,300]=33\n");
  ASSERT_EQ(matrix.size(), 3);
}
References sparse::Matrix< T, N_DIMS >::size().
TEST() [9/9]
TEST (sparse_matrix , reassignment)
Definition at line 69 of file matrix_gtest.cpp.
{
  sparse::Matrix<int> matrix;
  ((matrix[100][100] = 314) = 0) = 217;
  ASSERT_EQ(matrix[100][100], 217);
}