sparse_matrix: sparse::Matrix< T, N_DIMS > Struct Template Reference
sparse::Matrix< T, N_DIMS > Struct Template Reference
sparse matrix with N_DIMS "infinite" dimensions
#include <matrix.hpp>
Public Types
using IndexType = details::IndexType< N_DIMS >
using IndexTypeConstShared = details::IndexTypeConstShared< N_DIMS >
using HeadShiftIndex = details::ShiftIndex< T, N_DIMS, 1 >
using const_iterator = typename std::map< IndexType, T >::const_iterator
Public Member Functions
ctor
Matrix (T const &default_value) noexcept(noexcept(T(default_value)))
Matrix (T &&default_value=T{}) noexcept(noexcept(T(std::forward< T >(default_value))))
Matrix (Matrix const &other)
Matrix (Matrix &&other) noexcept
assignment
Matrix & operator= (Matrix const &other)
Matrix & operator= (Matrix &&other) noexcept
details::CellAccessor
T const & get (IndexTypeConstShared idx) const noexcept override
void set (IndexTypeConstShared idx, T const &value) noexcept(noexcept(T(value))) override
void set (IndexTypeConstShared idx, T &&value) noexcept(noexcept(T(std::forward< T >(value)))) override
index
HeadShiftIndex operator[] (size_t idx1)
misc
size_t size () const noexcept
iter
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Public Member Functions inherited from sparse::details::CellAccessor< T, N_DIMS >
virtual T const & get (IndexTypeConstShared< N_DIMS >) const noexcept=0
virtual void set (IndexTypeConstShared< N_DIMS > idx, T const &value) noexcept(noexcept(T(value)))=0
virtual void set (IndexTypeConstShared< N_DIMS > idx, T &&value) noexcept(noexcept(T(std::forward< T >(value))))=0
Private Member Functions
void swap (Matrix &&other) noexcept
Private Attributes
std::map< IndexType, T > _map
T _default
Friends
friends
std::ostream & operator<< (std::ostream &out, Matrix const &matrix)
Detailed Description
template<std::copyable T, size_t N_DIMS>
struct sparse::Matrix< T, N_DIMS >
sparse matrix with N_DIMS "infinite" dimensions
Note
Usage examlple:
Matrix<int, 3> m(-1);
m[100][200][300] = 1;
assert(m[100][200][300] == 1);
assert(m[1][2][3] == -1);
assert(m.size() == 1);
m[100][200][300] = -1;
assert(m.size() == 0);
Template Parameters
T copyable type of matrix element
N_DIMS number of matrix dimensions (>= 1)
Definition at line 114 of file matrix.hpp.
Member Typedef Documentation
const_iterator
template<std::copyable T, size_t N_DIMS> using sparse::Matrix< T, N_DIMS >::const_iterator = typename std::map<IndexType, T>::const_iterator
Definition at line 121 of file matrix.hpp.
HeadShiftIndex
template<std::copyable T, size_t N_DIMS> using sparse::Matrix< T, N_DIMS >::HeadShiftIndex = details::ShiftIndex<T, N_DIMS, 1>
Definition at line 119 of file matrix.hpp.
IndexType
template<std::copyable T, size_t N_DIMS> using sparse::Matrix< T, N_DIMS >::IndexType = details::IndexType<N_DIMS>
Definition at line 117 of file matrix.hpp.
IndexTypeConstShared
template<std::copyable T, size_t N_DIMS> using sparse::Matrix< T, N_DIMS >::IndexTypeConstShared = details::IndexTypeConstShared<N_DIMS>
Definition at line 118 of file matrix.hpp.
Constructor & Destructor Documentation
Matrix() [1/4]
template<std::copyable T, size_t N_DIMS> sparse::Matrix< T, N_DIMS >::Matrix (T const & default_value) inline noexcept
Definition at line 137 of file matrix.hpp.
: _default{default_value} {}
Matrix() [2/4]
template<std::copyable T, size_t N_DIMS> sparse::Matrix< T, N_DIMS >::Matrix (T && default_value = T{}) inline noexcept
Definition at line 138 of file matrix.hpp.
                              {}) noexcept(noexcept(T(std::forward<T>(default_value))))
      : _default{std::forward<T>(default_value)} {}
Matrix() [3/4]
template<std::copyable T, size_t N_DIMS> sparse::Matrix< T, N_DIMS >::Matrix (Matrix< T, N_DIMS > const & other) inline
Definition at line 140 of file matrix.hpp.
: _map(other._map), _default(other._default) {}
Matrix() [4/4]
template<std::copyable T, size_t N_DIMS> sparse::Matrix< T, N_DIMS >::Matrix (Matrix< T, N_DIMS > && other) inline noexcept
Definition at line 141 of file matrix.hpp.
{ swap(std::forward<T>(other)); }
References sparse::Matrix< T, N_DIMS >::swap().
Member Function Documentation
begin()
template<std::copyable T, size_t N_DIMS> const_iterator sparse::Matrix< T, N_DIMS >::begin () const inline noexcept
Definition at line 203 of file matrix.hpp.
{ return _map.cbegin(); }
References sparse::Matrix< T, N_DIMS >::_map.
cbegin()
template<std::copyable T, size_t N_DIMS> const_iterator sparse::Matrix< T, N_DIMS >::cbegin () const inline noexcept
Definition at line 205 of file matrix.hpp.
{ return _map.cbegin(); }
References sparse::Matrix< T, N_DIMS >::_map.
cend()
template<std::copyable T, size_t N_DIMS> const_iterator sparse::Matrix< T, N_DIMS >::cend () const inline noexcept
Definition at line 206 of file matrix.hpp.
{ return _map.cend(); }
References sparse::Matrix< T, N_DIMS >::_map.
end()
template<std::copyable T, size_t N_DIMS> const_iterator sparse::Matrix< T, N_DIMS >::end () const inline noexcept
Definition at line 204 of file matrix.hpp.
{ return _map.cend(); }
References sparse::Matrix< T, N_DIMS >::_map.
get()
template<std::copyable T, size_t N_DIMS> T const & sparse::Matrix< T, N_DIMS >::get (IndexTypeConstShared idx) const inline override noexcept
Definition at line 161 of file matrix.hpp.
{
    auto const& it = _map.find(*idx.get());
    if (it == _map.end()) {
      return _default;
    }
    return it->second;
  }
References sparse::Matrix< T, N_DIMS >::_default, and sparse::Matrix< T, N_DIMS >::_map.
operator=() [1/2]
template<std::copyable T, size_t N_DIMS> Matrix & sparse::Matrix< T, N_DIMS >::operator= (Matrix< T, N_DIMS > && other) inline noexcept
Definition at line 153 of file matrix.hpp.
{
    swap(std::forward<T>(other));
    return *this;
  }
References sparse::Matrix< T, N_DIMS >::swap().
operator=() [2/2]
template<std::copyable T, size_t N_DIMS> Matrix & sparse::Matrix< T, N_DIMS >::operator= (Matrix< T, N_DIMS > const & other) inline
Definition at line 146 of file matrix.hpp.
{
    if (this != &other) {
      _map = other._map;          // copy-assignment
      _default = other._default;  // copy-assignment
    }
    return *this;
  }
References sparse::Matrix< T, N_DIMS >::_default, and sparse::Matrix< T, N_DIMS >::_map.
operator[]()
template<std::copyable T, size_t N_DIMS> HeadShiftIndex sparse::Matrix< T, N_DIMS >::operator[] (size_t idx1) inline
Definition at line 190 of file matrix.hpp.
{
    LOG_PPF;
    return HeadShiftIndex(this, details::IndexTypeShared<N_DIMS>(new IndexType{idx1}));
  }
References LOG_PPF.
set() [1/2]
template<std::copyable T, size_t N_DIMS> void sparse::Matrix< T, N_DIMS >::set (IndexTypeConstShared idx, T && value) inline override noexcept
Definition at line 176 of file matrix.hpp.
{
    if (value == _default) {
      _map.erase(*idx.get());
    } else {
      // _map.emplace(std::piecewise_construct, std::forward_as_tuple(idx),
      // std::forward_as_tuple(value)); T::T(const T&) _map.try_emplace(idx,
      // value);
      _map.insert_or_assign(*idx.get(), std::forward<T>(value));
    }
  }
References sparse::Matrix< T, N_DIMS >::_default, and sparse::Matrix< T, N_DIMS >::_map.
set() [2/2]
template<std::copyable T, size_t N_DIMS> void sparse::Matrix< T, N_DIMS >::set (IndexTypeConstShared idx, T const & value) inline override noexcept
Definition at line 168 of file matrix.hpp.
{
    if (value == _default) {
      _map.erase(*idx.get());
    } else {
      // _map[idx] = value;
      _map.insert_or_assign(*idx.get(), value);
    }
  }
References sparse::Matrix< T, N_DIMS >::_default, and sparse::Matrix< T, N_DIMS >::_map.
size()
template<std::copyable T, size_t N_DIMS> size_t sparse::Matrix< T, N_DIMS >::size () const inline noexcept
Definition at line 198 of file matrix.hpp.
{ return _map.size(); }
References sparse::Matrix< T, N_DIMS >::_map.
Referenced by main(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
swap()
template<std::copyable T, size_t N_DIMS> void sparse::Matrix< T, N_DIMS >::swap (Matrix< T, N_DIMS > && other) inline private noexcept
Definition at line 129 of file matrix.hpp.
{
    std::swap(_map, other._map);
    std::swap(_default, other._default);
  }
References sparse::Matrix< T, N_DIMS >::_default, and sparse::Matrix< T, N_DIMS >::_map.
Referenced by sparse::Matrix< T, N_DIMS >::Matrix(), and sparse::Matrix< T, N_DIMS >::operator=().
Friends And Related Symbol Documentation
operator<<
template<std::copyable T, size_t N_DIMS> std::ostream & operator<< (std::ostream & out, Matrix< T, N_DIMS > const & matrix) friend
Definition at line 211 of file matrix.hpp.
{
    for (auto const& cell : matrix) {
      auto const& [idx, value] = cell;
      out << "[" << idx[0];
      for (size_t i = 1; i < N_DIMS; ++i) out << "," << idx[i];
      out << "]=" << value << "\n";
    }
    return out;
  }
Member Data Documentation
_default
template<std::copyable T, size_t N_DIMS> T sparse::Matrix< T, N_DIMS >::_default private
Definition at line 127 of file matrix.hpp.
Referenced by sparse::Matrix< T, N_DIMS >::get(), sparse::Matrix< T, N_DIMS >::operator=(), sparse::Matrix< T, N_DIMS >::set(), sparse::Matrix< T, N_DIMS >::set(), and sparse::Matrix< T, N_DIMS >::swap().
_map
template<std::copyable T, size_t N_DIMS> std::map<IndexType, T> sparse::Matrix< T, N_DIMS >::_map private
std::map is used to store elements because matrix iterator outputs elemenets sorted by index.
Definition at line 124 of file matrix.hpp.
Referenced by sparse::Matrix< T, N_DIMS >::begin(), sparse::Matrix< T, N_DIMS >::cbegin(), sparse::Matrix< T, N_DIMS >::cend(), sparse::Matrix< T, N_DIMS >::end(), sparse::Matrix< T, N_DIMS >::get(), sparse::Matrix< T, N_DIMS >::operator=(), sparse::Matrix< T, N_DIMS >::set(), sparse::Matrix< T, N_DIMS >::set(), sparse::Matrix< T, N_DIMS >::size(), and sparse::Matrix< T, N_DIMS >::swap().
The documentation for this struct was generated from the following file:
src/sparse/matrix.hpp